### ISSUE TITLE
TypeError: ArrayField.empty_field: return type `None` is not a `allennlp.data.fields.field.Field`.

### ISSUE THREAD

**Issue by Minitour** [fractalego/pynsett#15]
Hi, I recently tried to install this framework (as a library in another project and as a project itself).

Every time I try to run the code I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/pynsett/server/__init__.py", line 1, in <module>
    from pynsett.server.server import pynsett_app
  File "/usr/local/pynsett/server/server.py", line 8, in <module>
    from pynsett.auxiliary.prior_knowedge import get_wikidata_knowledge
  File "/usr/local/pynsett/auxiliary/prior_knowedge.py", line 3, in <module>
    from pynsett.knowledge import Knowledge
  File "/usr/local/pynsett/knowledge/__init__.py", line 5, in <module>
    from pynsett.discourse import Discourse
  File "/usr/local/pynsett/discourse/__init__.py", line 1, in <module>
    from .discourse import Discourse
  File "/usr/local/pynsett/discourse/discourse.py", line 7, in <module>
    from pynsett.discourse.anaphora import AllenCoreferenceVisitorsFactory
  File "/usr/local/pynsett/discourse/anaphora.py", line 6, in <module>
    from allennlp.predictors.predictor import Predictor
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/__init__.py", line 9, in <module>
    from allennlp.predictors.predictor import Predictor
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 8, in <module>
    from allennlp.data import DatasetReader, Instance
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 4, in <module>
    from allennlp.data.instance import Instance
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/fields/array_field.py", line 47, in ArrayField
    @overrides
  File "/usr/local/lib/python3.6/site-packages/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/usr/local/lib/python3.6/site-packages/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/usr/local/lib/python3.6/site-packages/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/usr/local/lib/python3.6/site-packages/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/usr/local/lib/python3.6/site-packages/overrides/signature.py", line 288, in ensure_return_type_compatibility
    f"{method_name}: return type `{sub_return}` is not a `{super_return}`."
TypeError: ArrayField.empty_field: return type `None` is not a `allennlp.data.fields.field.Field`.
```

I got this error after I ran the docker container using an image I built myself from the dockerfile on the master branch.

**Comment by fractalego** [comment]
Thank you, I can have a look. What code were you running? What triggers this error?

**Comment by fractalego** [comment]
Uhm a quick googling suggests to try:
pip install overrides==3.1.0

It seems related to how allen nlp is installed.

**Comment by Minitour** [comment]
This is what I am trying to do:

```python
from fastapi import FastAPI
from pynsett.writer.drt_triplets_writer import DRTTripletsWriter
from pynsett.discourse import Discourse

app = FastAPI()


@app.get("/")
def read_root():
    text = 'The brown dog jumped over the lazy fox'
    discourse = Discourse(text)
    writer = DRTTripletsWriter()
    triplets = discourse.apply(writer)
    print(triplets)
    return {"Hello": "World"}

```

My requirements file:
```
pynsett
fastapi
uvicorn
jmespath
more-itertools
```

The docker file:
```
FROM python:3.6

RUN apt-get update
RUN apt-get install -qq -y build-essential python-dev

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY ./start.sh /code/start.sh

RUN chmod +x /code/start.sh
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN python -m spacy download en_core_web_lg
RUN python -m pynsett download
COPY ./rela /code/rela

CMD ["./start.sh"]
```

The error:
(Same as above)

From the stack trace, it doesn't look as if anything is being executed, but the issue occurs as a result of an import chain.

**Comment by fractalego** [comment]
Uhm yes it is seems related to the imports. Allennlp might have changed something since my last code maintenance. Have you tried the pip install above?


On a related note, if you are looking for relation extraction I am maintaining a more recent code on HuggingFace
https://huggingface.co/fractalego/fewrel-zero-shot

**Comment by Minitour** [comment]
I just tried it and it seems to solve that issue. I am now getting a different error from Scikit to which the solution is most likely the same (`ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'`)
I am currently most interested in the neo-davidosnian representation, but I will be sure to check out your project on HuggingFace.

Thanks for the quick response!

**Comment by Minitour** [comment]
Was able to finally solve it and actually run the code. Thanks for all the help.

### Finally solution:
Update requirements file to include the following:
```
more-itertools
overrides==3.1.0
scikit-learn==0.22.2**
```

Download nltk (in addition to spacy and pynsett)
```
python -m nltk.downloader punkt
```

My final dockerfile looks like this:

```
FROM python:3.6

RUN apt-get update
RUN apt-get install -qq -y build-essential python-dev

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY ./start.sh /code/start.sh

RUN chmod +x /code/start.sh
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN python -m spacy download en_core_web_lg
RUN python -m pynsett download
RUN python -m nltk.downloader punkt

COPY ./rela /code/rela

CMD ["./start.sh"]
```
